server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/identity_service_db
    username: identity
    password: identity
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

identity:
  jwt:
    issuer: http://localhost:8083
    access-token-ttl: PT30M
    key-file: ./keys/identity-jwk.json