spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8083/.well-known/jwks.json
          issuer-uri: http://localhost:8083
  datasource:
    url: jdbc:postgresql://localhost:5433/event_service_db
    username: event
    password: event
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        enable.idempotence: true
    consumer:
      group-id: event-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
    listener:
      ack-mode: record

outbox:
  poll-interval-ms: 2000
  batch-size: 50

logging:
  level:
    org.hibernate.SQL: debug

management:
  endpoints:
    web:
      exposure:
        include: health,metrics